<script setup lang="ts">
useSeoMeta({
  title: 'codewright',
  description:
    'Human-supervised AI-assisted QA for EU startups. Signed compliance reports tied to NIS2, GDPR, and eIDAS 2.0.',
  ogTitle: 'codewright — Globaltechno work'
});

const stack = [
  'TypeScript',
  'Node.js',
  'Playwright',
  'Vitest',
  'k6',
  'OWASP ZAP',
  'PostgreSQL',
  'AWS'
];
</script>

<template>
  <div class="case-study">
    <section class="cs-hero section section--light">
      <div class="cs-hero__inner section__inner section__inner--narrow">
        <SharedScrollReveal>
          <p class="cs-hero__eyebrow">
            <NuxtLink to="/work">Work</NuxtLink>
            <span aria-hidden="true">·</span>
            <span>2025</span>
          </p>
          <h1 class="cs-hero__title text-balance">codewright</h1>
          <p class="cs-hero__role">Product · QA infrastructure for EU startups</p>
          <p class="cs-hero__summary">
            Human-supervised, AI-assisted quality assurance for EU startups. Signed compliance-ready test reports
            tied to NIS2, GDPR, and eIDAS 2.0 — the missing artifact between AI-generated code and regulator,
            investor, or enterprise sign-off.
          </p>
          <a
            href="https://codewright.co"
            target="_blank"
            rel="noopener noreferrer"
            class="cs-hero__live"
          >
            codewright.co <span aria-hidden="true">↗</span>
          </a>
        </SharedScrollReveal>
      </div>
    </section>

    <section class="cs-cover section section--light">
      <div class="cs-cover__inner section__inner">
        <SharedScrollReveal direction="scale">
          <div class="cs-cover__media" aria-hidden="true">
            <span class="cs-cover__title">codewright</span>
            <span class="cs-cover__sub">Signed off.</span>
          </div>
        </SharedScrollReveal>
      </div>
    </section>

    <section class="cs-block section section--light">
      <div class="cs-block__inner section__inner section__inner--narrow">
        <SharedScrollReveal>
          <span class="section-label">Problem</span>
          <h2 class="cs-block__heading text-balance">
            AI writes your code. Nobody signs off on it.
          </h2>
          <p class="cs-block__body">
            AI coding tools — Claude Code, Copilot, Cursor — ship code at unprecedented speed. But the artifacts
            investors, enterprise procurement teams, and regulators need haven't kept up. "The AI tested it" doesn't
            close due diligence. NIS2, GDPR, and eIDAS 2.0 want named professionals behind sign-offs, not autogenerated
            test logs.
          </p>
          <p class="cs-block__body">
            EU startups using AI tooling were stuck: their velocity was real, but the evidence trail wasn't.
          </p>
        </SharedScrollReveal>
      </div>
    </section>

    <section class="cs-block section section--alt">
      <div class="cs-block__inner section__inner section__inner--narrow">
        <SharedScrollReveal>
          <span class="section-label">Approach</span>
          <h2 class="cs-block__heading text-balance">
            Three tiers. Every engagement ends with a signed PDF.
          </h2>
          <p class="cs-block__body">
            We packaged the offer as three monthly tiers — Starter, Growth, Scale (€299 – €999 / month) — each
            blending automation, hybrid testing, and human-led work:
          </p>
          <ul class="cs-block__list">
            <li>
              <strong>Automated</strong> — regression, performance, accessibility, API testing run continuously.
            </li>
            <li>
              <strong>Hybrid</strong> — functional, integration, end-to-end, and AI-system testing supervised by
              an engineer.
            </li>
            <li>
              <strong>Human-led</strong> — payments testing, UAT, pre-launch sweeps, penetration testing,
              usability review.
            </li>
          </ul>
          <p class="cs-block__body">
            Every engagement ends with a signed PDF report carrying a named professional's certification, mapped
            to the relevant compliance framework. The artifact a customer or auditor actually wants.
          </p>
        </SharedScrollReveal>
      </div>
    </section>

    <section class="cs-block section section--light">
      <div class="cs-block__inner section__inner section__inner--narrow">
        <SharedScrollReveal>
          <span class="section-label">Outcome</span>
          <h2 class="cs-block__heading text-balance">
            EU startups ship fast and keep their evidence trail intact.
          </h2>
          <p class="cs-block__body">
            Customers close enterprise deals with the signed report in hand. Investor due diligence moves faster.
            Compliance documentation is reusable across audits instead of being rebuilt each cycle. The signed PDF
            is the deliverable customers reach for first.
          </p>
        </SharedScrollReveal>
      </div>
    </section>

    <section class="cs-stack section section--light">
      <div class="cs-stack__inner section__inner section__inner--narrow">
        <SharedScrollReveal>
          <span class="section-label">Stack</span>
          <ul class="cs-stack__list">
            <li v-for="item in stack" :key="item" class="cs-stack__item">{{ item }}</li>
          </ul>
        </SharedScrollReveal>
      </div>
    </section>

    <HomeClosingCtaSection />
  </div>
</template>

<style scoped>
.cs-hero {
  padding-top: clamp(7rem, 12vw, 10rem);
  padding-bottom: clamp(2rem, 4vw, 4rem);
}

.cs-hero__inner {
  max-width: var(--max-width-narrow);
  margin: 0 auto;
}

.cs-hero__eyebrow {
  display: inline-flex;
  align-items: center;
  gap: 0.6rem;
  font-family: var(--font-mono);
  font-size: 0.72rem;
  letter-spacing: 0.18em;
  text-transform: uppercase;
  color: var(--ink-mute);
  margin-bottom: 1.5rem;
}

.cs-hero__eyebrow a {
  color: var(--ink-mute);
  border-bottom: 1px solid transparent;
  transition: color var(--duration-fast) ease, border-color var(--duration-fast) ease;
}

.cs-hero__eyebrow a:hover {
  color: var(--accent);
  border-bottom-color: var(--accent);
}

.cs-hero__title {
  font-size: clamp(3rem, 9vw, 7rem);
  letter-spacing: -0.04em;
  line-height: 1.0;
  margin: 0 0 1.5rem;
}

.cs-hero__role {
  font-family: var(--font-mono);
  font-size: 0.85rem;
  letter-spacing: 0.04em;
  color: var(--ink-mute);
  margin-bottom: 2rem;
}

.cs-hero__summary {
  font-size: clamp(1.15rem, 1.7vw, 1.35rem);
  line-height: 1.55;
  color: var(--ink);
  max-width: 60ch;
  margin-bottom: 2rem;
}

.cs-hero__live {
  display: inline-flex;
  align-items: center;
  gap: 0.4rem;
  font-family: var(--font-mono);
  font-size: 0.85rem;
  letter-spacing: 0.04em;
  color: var(--ink);
  border-bottom: 1px solid var(--ink);
  padding-bottom: 2px;
  transition: color var(--duration-fast) ease, border-color var(--duration-fast) ease;
}

.cs-hero__live:hover {
  color: var(--accent);
  border-bottom-color: var(--accent);
}

.cs-cover {
  padding-top: 2rem;
  padding-bottom: clamp(4rem, 8vw, 7rem);
}

.cs-cover__media {
  aspect-ratio: 16 / 9;
  border-radius: var(--radius-xl);
  background:
    radial-gradient(ellipse at 75% 30%, var(--accent-wash), transparent 55%),
    linear-gradient(135deg, #0E0E10 0%, #1A1A2E 100%);
  color: var(--paper);
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 0.75rem;
  border: 1px solid var(--line);
  overflow: hidden;
}

.cs-cover__title {
  font-family: var(--font-display);
  font-size: clamp(3rem, 8vw, 6rem);
  letter-spacing: -0.04em;
  color: var(--paper);
}

.cs-cover__sub {
  font-family: var(--font-mono);
  font-size: 0.85rem;
  letter-spacing: 0.18em;
  text-transform: uppercase;
  color: var(--accent);
}

.cs-block__inner {
  max-width: var(--max-width-narrow);
  margin: 0 auto;
}

.cs-block__heading {
  margin: 0.25rem 0 2rem;
  font-size: clamp(1.75rem, 4vw, 2.75rem);
  letter-spacing: -0.025em;
  line-height: 1.1;
}

.cs-block__body {
  font-size: 1.075rem;
  line-height: 1.7;
  color: var(--ink);
  max-width: 62ch;
  margin-bottom: 1.25rem;
}

.cs-block__body:last-child {
  margin-bottom: 0;
}

.cs-block__list {
  list-style: none;
  margin: 1.5rem 0;
  padding: 0;
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.cs-block__list li {
  position: relative;
  padding-left: 1.75rem;
  font-size: 1.025rem;
  line-height: 1.65;
  color: var(--ink);
}

.cs-block__list li::before {
  content: '';
  position: absolute;
  left: 0;
  top: 0.7rem;
  width: 14px;
  height: 1px;
  background: var(--accent);
}

.cs-block__list li strong {
  font-weight: 500;
  color: var(--ink);
}

.cs-stack__inner {
  max-width: var(--max-width-narrow);
  margin: 0 auto;
}

.cs-stack__list {
  list-style: none;
  margin: 1rem 0 0;
  padding: 0;
  display: flex;
  flex-wrap: wrap;
  gap: 0.6rem;
}

.cs-stack__item {
  font-family: var(--font-mono);
  font-size: 0.78rem;
  letter-spacing: 0.04em;
  padding: 0.4rem 0.85rem;
  border: 1px solid var(--line);
  border-radius: var(--radius-full);
  color: var(--ink);
  background: var(--paper-soft);
}
</style>
